'use client';
import { AppSidebar } from '../../components/AppSidebar';
import { FormEvent, useEffect, useState } from 'react';
import styles from './page.module.css';
type Reply={id:string;shortcut:string;title:string;body:string;category:string;isActive:boolean};
const empty={shortcut:'',title:'',body:'',category:'General'};
export default function QuickRepliesPage(){
 const [replies,setReplies]=useState<Reply[]>([]),[form,setForm]=useState(empty),[editing,setEditing]=useState<Reply|null>(null),[name,setName]=useState('Empresa'),[message,setMessage]=useState(''),[saving,setSaving]=useState(false);
 async function load(){try{const r=await fetch(`/api/quick-replies`,{cache:'no-store'});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'No se pudo cargar.');setReplies(d.quickReplies||[]);setName(d.company?.name||'Empresa')}catch(e){setMessage(e instanceof Error?e.message:'No se pudo cargar.')}} useEffect(()=>{void load()},[]);
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setMessage('');try{const endpoint=editing?`/api/quick-replies?id=${editing.id}`:`/api/quick-replies`;const r=await fetch(endpoint,{method:editing?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'No se pudo guardar.');setForm(empty);setEditing(null);await load()}catch(e){setMessage(e instanceof Error?e.message:'No se pudo guardar.')}finally{setSaving(false)}}
 async function toggle(reply:Reply){const r=await fetch(`/api/quick-replies?id=${reply.id}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({isActive:!reply.isActive})});if(!r.ok){setMessage('No se pudo actualizar.');return}await load()}
 async function remove(reply:Reply){if(!confirm(`¿Eliminar /${reply.shortcut}?`))return;const r=await fetch(`/api/quick-replies?id=${reply.id}`,{method:'DELETE'});if(!r.ok){setMessage('No se pudo eliminar.');return}await load()}
 return <main className={styles.shell}><AppSidebar companyName={name}/><section className={styles.workspace}><header className={styles.header}><div><p>CONFIGURACIÓN</p><h1>Respuestas rápidas · {name}</h1><span>El asesor escribe <b>/</b> en la bandeja, selecciona un atajo y revisa el texto antes de enviar.</span></div><button onClick={()=>location.assign('/configuracion')}>← Volver</button></header><div className={styles.layout}><form className={styles.form} onSubmit={save}><h2>{editing?`Editar /${editing.shortcut}`:'Nueva respuesta rápida'}</h2><label>Atajo<div className={styles.shortcut}>/<input value={form.shortcut} onChange={e=>setForm({...form,shortcut:e.target.value.replace(/^\//,'')})} placeholder="envio"/></div></label><label>Título interno<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Información de envíos"/></label><label>Categoría<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Texto<textarea value={form.body} onChange={e=>setForm({...form,body:e.target.value})} rows={8} placeholder="Hola 😊 ..."/></label>{message?<p className={styles.message}>{message}</p>:null}<button className={styles.save} disabled={saving}>{saving?'Guardando…':editing?'Guardar cambios':'Crear respuesta'}</button>{editing?<button type="button" onClick={()=>{setEditing(null);setForm(empty)}}>Cancelar</button>:null}</form><section className={styles.list}><h2>Atajos</h2>{!replies.length?<p>Aún no hay respuestas. Crea por ejemplo <b>/envio</b> o <b>/tallas</b>.</p>:replies.map(reply=><article className={!reply.isActive?styles.off:''} key={reply.id}><div><code>/{reply.shortcut}</code><small>{reply.category}</small></div><h3>{reply.title}</h3><p>{reply.body}</p><footer><button onClick={()=>{setEditing(reply);setForm({shortcut:reply.shortcut,title:reply.title,body:reply.body,category:reply.category})}}>Editar</button><button onClick={()=>void toggle(reply)}>{reply.isActive?'Desactivar':'Activar'}</button><button onClick={()=>void remove(reply)}>Eliminar</button></footer></article>)}</section></div></section></main>
}
