'use client';
import {useEffect,useState,FormEvent} from 'react';
import {AppSidebar} from '../../components/AppSidebar';
import styles from './page.module.css';
const COMPANY=process.env.NEXT_PUBLIC_CHATPRO_COMPANY||'atogob';
type Day={dayOfWeek:number;label:string;isOpen:boolean;startTime:string;endTime:string};
type Cfg={humanAttentionEnabled:boolean;autoReturnToAiHours:number;outsideHoursMessage:string;hours:Day[]};
export default function Page(){const [c,setC]=useState<Cfg|null>(null),[name,setName]=useState('Empresa'),[msg,setMsg]=useState(''),[saving,setSaving]=useState(false);
useEffect(()=>{fetch(`/api/support-settings?company=${encodeURIComponent(COMPANY)}`,{cache:'no-store'}).then(r=>r.json()).then(d=>{if(!d.ok)throw Error(d.error);setC(d.configuration);setName(d.company?.name||'Empresa')}).catch(e=>setMsg(e.message||'No se pudo cargar.'))},[]);
const day=(id:number,x:Partial<Day>)=>setC(v=>v?{...v,hours:v.hours.map(d=>d.dayOfWeek===id?{...d,...x}:d)}:v);
async function save(e:FormEvent){e.preventDefault();if(!c)return;setSaving(true);setMsg('');try{const r=await fetch(`/api/support-settings?company=${encodeURIComponent(COMPANY)}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(c)}),d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||'No se pudo guardar.');setMsg(d.message||'Guardado.')}catch(e){setMsg(e instanceof Error?e.message:'Error')}finally{setSaving(false)}}
return <main className={styles.shell}><AppSidebar companyName={name}/><section className={styles.workspace}><header><div><p>CONFIGURACIÓN</p><h1>Horarios y atención · {name}</h1><span>La IA atiende 24/7. Este horario controla la atención de asesores.</span></div><button onClick={()=>location.assign('/configuracion')}>← Volver</button></header>{!c?<div><p>Cargando…</p>{msg?<p className={styles.msg}>{msg}</p>:null}</div>:<form onSubmit={save}><article><div className={styles.head}><div><h2>Atención humana</h2><small>Fuera de horario, los casos que requieren persona quedarán pendientes.</small></div><label><input type="checkbox" checked={c.humanAttentionEnabled} onChange={e=>setC({...c,humanAttentionEnabled:e.target.checked})}/> {c.humanAttentionEnabled?'Activa':'Pausada'}</label></div><label>Devolver automáticamente a IA después de <input type="number" min="1" max="168" value={c.autoReturnToAiHours} onChange={e=>setC({...c,autoReturnToAiHours:Number(e.target.value)||1})}/> horas sin actividad del asesor</label><label>Mensaje para cuando se requiere asesor fuera de horario<textarea rows={4} value={c.outsideHoursMessage} onChange={e=>setC({...c,outsideHoursMessage:e.target.value})} placeholder="Nuestro equipo te atenderá dentro del horario de atención. Mientras tanto, puedo ayudarte con productos, tallas, envíos y pagos."/></label></article><article><h2>Horario general</h2>{c.hours.map(d=><div className={styles.day} key={d.dayOfWeek}><label><input type="checkbox" checked={d.isOpen} onChange={e=>day(d.dayOfWeek,{isOpen:e.target.checked})}/> <b>{d.label}</b></label>{d.isOpen?<span><input type="time" value={d.startTime} onChange={e=>day(d.dayOfWeek,{startTime:e.target.value})}/> a <input type="time" value={d.endTime} onChange={e=>day(d.dayOfWeek,{endTime:e.target.value})}/></span>:<em>Cerrado</em>}</div>)}</article>{msg&&<p className={styles.msg}>{msg}</p>}<button className={styles.save} disabled={saving}>{saving?'Guardando…':'Guardar horarios y atención'}</button></form>}</section></main>}
