'use client';
import {FormEvent,useEffect,useState} from 'react';
import {AppSidebar} from '../../components/AppSidebar';
import styles from './page.module.css';
type Area={id:string;name:string;description:string;isActive:boolean;isDefault:boolean};
type Data={ok?:boolean;error?:string;message?:string;company?:{name?:string};areas?:Area[]};
export default function Page(){
 const[nameCompany,setNameCompany]=useState('Empresa'),[areas,setAreas]=useState<Area[]>([]),[name,setName]=useState(''),[description,setDescription]=useState(''),[editing,setEditing]=useState(''),[editName,setEditName]=useState(''),[editDesc,setEditDesc]=useState(''),[loading,setLoading]=useState(true),[working,setWorking]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState('');
 async function req(url:string,init?:RequestInit){const r=await fetch(url,{cache:'no-store',...init});const d=await r.json() as Data;if(!r.ok||!d.ok)throw Error(d.error||'No se pudo procesar.');return d;}
 async function load(){setLoading(true);try{const d=await req(`/api/service-areas`);setNameCompany(d.company?.name||'Empresa');setAreas(d.areas||[]);setError('')}catch(e){setError(e instanceof Error?e.message:'No se pudieron cargar.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function create(e:FormEvent){e.preventDefault();setWorking('create');try{const d=await req(`/api/service-areas`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,description})});setName('');setDescription('');setMessage(d.message||'Área creada.');await load()}catch(e){setError(e instanceof Error?e.message:'Error')}finally{setWorking('')}}
 async function update(a:Area,p:object){setWorking(a.id);try{const d=await req(`/api/service-areas/${a.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(p)});setMessage(d.message||'Actualizado.');setEditing('');await load()}catch(e){setError(e instanceof Error?e.message:'Error')}finally{setWorking('')}}
 async function remove(a:Area){if(!confirm(`¿Eliminar "${a.name}"?`))return;setWorking(a.id);try{const d=await req(`/api/service-areas/${a.id}`,{method:'DELETE'});setMessage(d.message||'Área eliminada.');await load()}catch(e){setError(e instanceof Error?e.message:'Error')}finally{setWorking('')}}
 return <main className={styles.shell}><AppSidebar companyName={nameCompany}/><section className={styles.workspace}><header className={styles.header}><div><p>CONFIGURACIÓN</p><h1>Áreas de atención · {nameCompany}</h1><span>Crea las áreas que usa tu empresa para repartir conversaciones.</span></div><button onClick={()=>location.assign('/configuracion')}>← Volver</button></header>{error&&<div className={styles.error}>{error}</div>}{message&&<div className={styles.success}>{message}</div>}<div className={styles.grid}><section className={styles.create}><p>NUEVA ÁREA</p><h2>Crear área</h2><form onSubmit={create}><label>Nombre<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ejemplo: Mayoristas"/></label><label>Descripción<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={4} placeholder="Qué tipo de casos atiende esta área."/></label><button className={styles.primary} disabled={!name.trim()||working==='create'}>{working==='create'?'Creando…':'Crear área'}</button></form></section><section className={styles.list}><div className={styles.listHead}><div><p>ÁREAS</p><h2>{loading?'Cargando…':`${areas.length} áreas configuradas`}</h2></div><button onClick={()=>void load()}>↻</button></div>{areas.map(a=><article className={!a.isActive?styles.inactive:''} key={a.id}>{editing===a.id?<div className={styles.edit}><label>Nombre<input value={editName} onChange={e=>setEditName(e.target.value)}/></label><label>Descripción<textarea rows={3} value={editDesc} onChange={e=>setEditDesc(e.target.value)}/></label><button className={styles.primary} onClick={()=>void update(a,{name:editName,description:editDesc})} disabled={!editName.trim()||working===a.id}>Guardar</button><button onClick={()=>setEditing('')}>Cancelar</button></div>:<><div><h3>{a.name} {a.isDefault&&<small>Inicial</small>} {!a.isActive&&<small>Inactiva</small>}</h3><span>{a.description||'Sin descripción.'}</span></div><div className={styles.actions}><button onClick={()=>{setEditing(a.id);setEditName(a.name);setEditDesc(a.description)}}>Editar</button><button onClick={()=>void update(a,{isActive:!a.isActive})} disabled={working===a.id}>{a.isActive?'Desactivar':'Activar'}</button>{!a.isDefault&&<button className={styles.delete} onClick={()=>void remove(a)} disabled={working===a.id}>Eliminar</button>}</div></>}</article>)}</section></div></section></main>
}
